### ISSUE TITLE
Windows flags the program as a virus

### ISSUE THREAD

**Issue by The-Nyla** [IWickGames/Minecraft-Server-Finder#3]
When downloading the program it's detected as containing a virus

![image](https://user-images.githubusercontent.com/79489385/172066836-0810061c-ad8c-48db-b864-66f646f31505.png)
![image](https://user-images.githubusercontent.com/79489385/172066852-caa617b9-143d-40bd-8e82-cef93297a02d.png)

**Comment by The-Nyla** [comment]
it would also be nice if you could explain why it gets flagged as containing a virus considering I can't view the code of the .exe file on github due to it's size and I can download it to open it bc it's flagged as a virus

**Comment by iwickdev** [comment]
Oh yeah that's an issue with PyInstaller the program that converts python projects to executable. For some reason no matter what you build into a exe it will be flagged by Windows Defender as a virus. There is not much I can do about that unfortunately, but you can always just run the main.py file in src after installing the requirements to use it without the exe file.

**Comment by iwickdev** [comment]
If I remember correctly it should require the following
https://pypi.org/project/PySimpleGUI/
https://pypi.org/project/mcstatus/
Once you get those installed via Pip it should work just as it would from the EXE file

**Comment by The-Nyla** [comment]
Thanks! I was wondering why it would be flagged, I’ll try that and thanks again for the text file exporter.

**Comment by The-Nyla** [comment]
I tried forking and the project and a ton of other things to see if I could try manually editing the exe but it didn’t work so that’s a much better solution, I tried main.pay earlier but didn’t know about the PySimpleGUI dependency

**Comment by iwickdev** [comment]
> Thanks! I was wondering why it would be flagged, I’ll try that and thanks again for the text file exporter.

Yeah I assume someone compiled something bad at some point with PyInstaller and now instead of flagging the actual part that's dangerous, they just detect everything.



> I tried forking and the project and a ton of other things to see if I could try manually editing the exe but it didn’t work so that’s a much better solution, I tried main.pay earlier but didn’t know about the PySimpleGUI dependency

You won't be able to edit to executable as it is a compiled version so you would have to compile it yourself by just installing pyinstaller and running the command to build main.py to the exe however I would just suggest at that point running main.py with python and not wasting time rebuilding it.

Also about PySimpleGUI is it not installing with PIP or is something not working right? It should just be a quick `pip install PySimpleGUI`. Those pypi links I sent you have the command to install you can easily copy. If it says it can't find PIP you can try using python with the -m flag such as `python -m pip install etc`. That will usually fix that.

**Comment by iwickdev** [comment]
Also if you are going to do that I would suggest using a VENV so you don't have to do anything to your python install. You can make one by running `python -m venv venv` then executing the activate script for your system should be in /venv/Scripts/Activate.bat or .ps1 or nothing depending on your system. If your on Windows the .bat or ps1 will be your choice otherwise the no file ending would be for Linux or Unix. Then just run pip commands as normal and it will install into the ENV instead of your python install.

**Comment by The-Nyla** [comment]
well for some reason it stopped flagging it as a virus when I downloaded it just now, and the exe works and everything, I assume you did something and whatever it was worked! Thank you!
